version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 99
