version: '3'

services:
  postgres:
    environment:
      POSTGRES_DB: metadeploy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sample_db_password
    volumes:
      - ./postgres:/var/lib/postgresql/data:delegated
    image: postgres:12.9
    restart: always

  redis:
    image: redis:6.2

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OMNIOUT_TOKEN: ${OMNIOUT_TOKEN}
    command: |
      /bin/bash -c 'while !</dev/tcp/postgres/5432; do echo "Waiting for postgres database to start..."; /bin/sleep 1; done; \
      /bin/sh /app/start-server.sh;'
    ports:
      - '8080:8080'
      - '8000:8000'
      # Storybook server
      - '6006:6006'
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - redis
    links:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
      DATABASE_URL: postgres://postgres:sample_db_password@postgres:5432/metadeploy
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
    volumes:
      - .:/app:cached
      - /app/node_modules
