version: '3'

services:
  postgres:
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data:delegated
    image: postgres:12.3
    ports:
      - '5432:5432/tcp'
    restart: always
  redis:
    image: redis:5.0
    ports:
      - '6379:6379'
  web:
    build:
      context: .
      args:
        - BUILD_ENV=development
      dockerfile: Dockerfile
    command: |
      /bin/bash -c 'while !</dev/tcp/postgres/5432; do echo "Waiting for postgres database to start..."; /bin/sleep 1; done; \
      /bin/sh /app/utility/start_server.sh;'
    ports:
      - '8080:8080'
      - '8000:8000'
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - redis
    links:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - /app/node_modules
