# Generated by Django 2.1.1 on 2018-10-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="preflight_flow_name",
            field=models.CharField(blank=True, max_length=256),
        )
    ]
