# Generated by Django 2.1 on 2018-08-28 20:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(
                default='#ffffff',
                max_length=18,
            ),
        ),
    ]
