# Generated by Django 2.1 on 2018-08-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon_url',
            field=models.URLField(
                blank=True,
                help_text=(
                        'This will take precedence over Color and the '
                        'SLDS Icons.'
                    ),
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='slds_icon_category',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', ''),
                    ('action', 'action'),
                    ('custom', 'custom'),
                    ('doctype', 'doctype'),
                    ('standard', 'standard'),
                    ('utility', 'utility'),
                ],
                default='',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='slds_icon_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
