# Generated by Django 2.1.2 on 2018-10-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_preflightresult"),
        ("api", "0002_user_alter_default_manager"),
    ]

    operations = []
