# Generated by Django 2.1.1 on 2018-09-06 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_product_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'token',
                    models.CharField(max_length=256),
                ),
                (
                    'instance_url',
                    models.URLField(),
                ),
                (
                    'package_url',
                    models.URLField(),
                ),
                (
                    'flow_name',
                    models.CharField(max_length=64),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
