# Generated by Django 2.1.1 on 2018-09-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='enqueued_at',
            field=models.DateTimeField(null=True),
        ),
    ]
