# Generated by Django 2.1.1 on 2018-09-07 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_version_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=128)),
                (
                    'tier',
                    models.CharField(
                        choices=[
                            ('primary', 'Primary'),
                            ('secondary', 'Secondary'),
                            ('additional', 'Additional'),
                        ],
                        default='primary',
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='version',
            name='is_production',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='version',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='api.Version',
            ),
        ),
    ]
