# Generated by Django 2.1.1 on 2018-09-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.CharField(
                choices=[
                    ('primary', 'primary'),
                    ('secondary', 'secondary'),
                    ('additional', 'additional'),
                ],
                default='primary',
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='version',
            name='label',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('product', 'label')},
        ),
    ]
