# Generated by Django 2.1.1 on 2018-09-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_job_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category_fk',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='api.ProductCategory',
            ),
        ),
    ]
