# Generated by Django 2.1.2 on 2018-10-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0007_preflightresult_is_valid")]

    operations = [
        migrations.AddField(
            model_name="preflightresult",
            name="plan",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="api.Plan"
            ),
        ),
        migrations.AddField(
            model_name="preflightresult",
            name="status",
            field=models.CharField(
                choices=[("started", "started"), ("complete", "complete")],
                default="started",
                max_length=64,
            ),
        ),
    ]
