# Generated by Django 2.1.1 on 2018-09-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_version_unique_together_and_other'), ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image',
        ),
    ]
