# Generated by Django 2.1.1 on 2018-09-12 16:40

from django.db import migrations


def forwards(apps, schema_editor):
    ProductCategory = apps.get_model('api', 'ProductCategory')
    Product = apps.get_model('api', 'Product')
    for product in Product.objects.all():
        category, _ = ProductCategory.get_or_create(title=product.category)
        product.category_fk = category
        product.save()


def backwards(apps, schema_editor):
    Product = apps.get_model('api', 'Product')
    for product in Product.objects.all():
        product.category = product.category_fk.title
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_category'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
