# Generated by Django 2.1.1 on 2018-09-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_migrate_category_to_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
