# Generated by Django 2.1.1 on 2018-09-12 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_image_url_to_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSlug',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(unique=True)),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text=(
                            'The most recently-created active slug for a '
                            'Product is the default slug.'
                        ),
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='api.Product',
                    ),
                ),
            ],
        ),
    ]
