# Generated by Django 2.1.2 on 2018-10-16 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0009_data_migrate_preflight")]

    operations = [
        migrations.AlterField(
            model_name="preflightresult",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.Plan"
            ),
        )
    ]
