# Generated by Django 2.1.1 on 2018-09-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_fk',
            new_name='category',
        ),
    ]
