# Generated by Django 2.1.1 on 2018-09-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_productslug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSlug',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(unique=True),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text=(
                            'The most recently-created active slug for '
                            'a Plan is the default slug.'
                        ),
                    ),
                ),
                (
                    'plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='api.Plan',
                    ),
                ),
            ],
        ),
    ]
