# Generated by Django 2.1.1 on 2018-09-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_image_url_to_image'),
        ('api', '0012_remove_token_fields_from_job'),
    ]

    operations = [
    ]
