# Generated by Django 2.1.2 on 2018-10-29 21:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_blank_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_steps',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=list,
            ),
        ),
    ]
