# Generated by Django 2.1.1 on 2018-09-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20180912_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='package_url',
            new_name='repo_url',
        ),
    ]
