# Generated by Django 2.1.1 on 2018-09-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_package_url_to_repo_url'),
        ('api', '0012_ensure_slugs'),
    ]

    operations = [
    ]
