# Generated by Django 2.1.2 on 2018-10-31 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_job_completed_steps'),
        ('api', '0014_preflightresult_blank_description'),
    ]

    operations = [
    ]
