# Generated by Django 2.1.1 on 2018-09-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_product_category_verbose_name'),
        ('api', '0016_add_validator_to_version'),
    ]

    operations = [
    ]
