# Generated by Django 2.1.2 on 2018-11-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0017_job_status")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="org_name",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="job",
            name="org_type",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
