# Generated by Django 2.1.1 on 2018-09-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20180917_2125'),
        ('api', '0015_no_null_product_category'),
    ]

    operations = [
    ]
