# Generated by Django 2.1.1 on 2018-09-18 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20180917_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planslug',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='productslug',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='planslug',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productslug',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planslug',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text=(
                    'If multiple slugs are active, we will default to '
                    'the most recent.'
                ),
            ),
        ),
        migrations.AlterField(
            model_name='planslug',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='productslug',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text=(
                    'If multiple slugs are active, we will default to '
                    'the most recent.'
                ),
            ),
        ),
        migrations.AlterUniqueTogether(
            name='planslug',
            unique_together={('slug', 'plan')},
        ),
    ]
