# Generated by Django 2.1.2 on 2018-11-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0019_job_is_public")]

    operations = [
        migrations.AddField(
            model_name="job", name="organization_url", field=models.URLField(blank=True)
        )
    ]
