# Generated by Django 2.1.1 on 2018-09-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_name_slug_parents_consistently'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planslug',
            unique_together=set(),
        ),
    ]
