# Generated by Django 2.1.2 on 2018-11-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_job_organization_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='post_install_message',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
