# Generated by Django 2.1.1 on 2018-09-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_fix_plan_slug_uniqueness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=1024)),
                ('is_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='preflight_message',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='step',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='api.Plan',
            ),
        ),
    ]
