# Generated by Django 2.1.4 on 2018-12-21 18:18

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("api", "0022_allow_private_product_version_plan"),
        ("api", "0023_merge_20181206_1759"),
        ("api", "0024_remove_version_visible_to"),
        ("api", "0025_auto_20181206_1831"),
        ("api", "0026_auto_20181206_1831"),
        ("api", "0027_merge_20181210_2232"),
        ("api", "0029_merge_20181213_2234"),
        ("api", "0030_merge_20181220_2216"),
    ]

    dependencies = [("api", "0021_plan_post_install_message")]

    operations = [
        migrations.CreateModel(
            name="AllowedList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "organization_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plan",
            name="visible_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.AllowedList",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="visible_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.AllowedList",
            ),
        ),
    ]
