# Generated by Django 2.1.4 on 2018-12-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0022_allow_canceled_result")]

    operations = [
        migrations.AddField(
            model_name="plan", name="is_listed", field=models.BooleanField(default=True)
        ),
        migrations.AddField(
            model_name="product",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="version",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
