# Generated by Django 2.1.1 on 2018-09-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_steps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ('order_key', 'name')},
        ),
        migrations.AddField(
            model_name='step',
            name='order_key',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
