# Generated by Django 2.1.4 on 2018-12-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_allow_canceled_result"),
        ("api", "0022_allow_private_product_version_plan"),
    ]

    operations = []
