# Generated by Django 2.1.4 on 2018-12-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_allow_canceled_result"),
        ("api", "0022_order_products_and_categories"),
    ]

    operations = []
