# Generated by Django 2.1.3 on 2018-12-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_change_default_on_results'),
        ('api', '0021_plan_post_install_message'),
    ]

    operations = [
    ]
