# Generated by Django 2.1.1 on 2018-09-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_order_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_recommended',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='step',
            name='kind',
            field=models.CharField(
                choices=[
                    ('metadata', 'Metadata'),
                    ('onetime', 'One Time Apex'),
                    ('managed', 'Managed Package'),
                    ('data', 'Data'),
                ],
                default='metadata',
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name='step',
            name='kind_icon',
            field=models.CharField(
                choices=[
                    ('metadata', 'metadata'),
                    ('onetime', 'onetime'),
                    ('managed', 'managed'),
                    ('data', 'data'),
                ],
                default='metadata',
                max_length=64,
            ),
        ),
    ]
