# Generated by Django 2.1.4 on 2018-12-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_merge_20181203_1618"),
        ("api", "0022_allow_canceled_result"),
    ]

    operations = []
