# Generated by Django 2.1.4 on 2018-12-10 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_merge_20181206_1541"),
        ("api", "0024_merge_20181206_1755"),
    ]

    operations = []
