# Generated by Django 2.1.4 on 2018-12-06 18:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0024_remove_version_visible_to")]

    operations = [
        migrations.CreateModel(
            name="AllowedList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "organization_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="plan", name="visible_to"),
        migrations.RemoveField(model_name="product", name="visible_to"),
    ]
