# Generated by Django 2.1.1 on 2018-09-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_extend_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
