# Generated by Django 2.1.1 on 2018-09-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_step_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='preflight_message',
            field=models.TextField(blank=True),
        ),
    ]
