# Generated by Django 2.1.4 on 2018-12-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_merge_20181210_2220"),
        ("api", "0024_change_product_ordering"),
    ]

    operations = []
