# Generated by Django 2.1.4 on 2018-12-06 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0025_auto_20181206_1831")]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="visible_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.AllowedList",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="visible_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.AllowedList",
            ),
        ),
    ]
