# Generated by Django 2.1.4 on 2018-12-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_merge_20181206_1541"),
        ("api", "0026_auto_20181206_1831"),
    ]

    operations = []
