# Generated by Django 2.1.4 on 2018-12-11 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_merge_20181210_2232"),
        ("api", "0025_merge_20181210_2243"),
    ]

    operations = []
