# Generated by Django 2.1.1 on 2018-09-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_preflight_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='repo_url',
            field=models.URLField(blank=True),
        ),
    ]
