# Generated by Django 2.1.4 on 2018-12-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0027_merge_20181211_1558")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="edited_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="preflightresult",
            name="edited_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
