# Generated by Django 2.1.1 on 2018-09-27 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_product_repo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='flow_name',
        ),
        migrations.AddField(
            model_name='job',
            name='flow_names',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                default=list,
                size=None,
            ),
        ),
    ]
