# Generated by Django 2.1.4 on 2018-12-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_add_job_preflight_edited_at"),
        ("api", "0027_merge_20181210_2232"),
    ]

    operations = []
