# Generated by Django 2.1.1 on 2018-09-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_flow_name_to_flow_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='flow_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
