# Generated by Django 2.1.4 on 2018-12-13 15:30

import hashid_field.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0028_add_job_preflight_edited_at")]

    operations = [
        migrations.AlterModelOptions(name="user", options={}),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet=(
                    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
                ),
                min_length=7,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
