# Generated by Django 2.1.4 on 2018-12-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_add_canceled_at_to_job_and_preflight"),
        ("api", "0029_result_exception_logs"),
    ]

    operations = []
