# Generated by Django 2.1.4 on 2018-12-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0029_result_exception_logs")]

    operations = [
        migrations.AddField(
            model_name="job", name="log", field=models.TextField(blank=True)
        )
    ]
