# Generated by Django 2.1.4 on 2018-12-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0029_user_hashid"), ("api", "0029_result_exception_logs")]

    operations = []
