# Generated by Django 2.1.4 on 2018-12-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_merge_20181213_2234"),
        ("api", "0029_result_exception_logs"),
    ]

    operations = []
