# Generated by Django 2.1.4 on 2018-12-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0022_allow_private_product_version_plan_squashed_0030_merge_20181220_2216",
        ),
        ("api", "0029_result_exception_logs"),
    ]

    operations = []
