# Generated by Django 2.1.4 on 2018-12-20 20:22

import sfdo_template_helpers.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0029_result_exception_logs")]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="post_install_message",
            field=sfdo_template_helpers.fields.MarkdownField(
                blank=True, property_suffix="_markdown"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="preflight_message",
            field=sfdo_template_helpers.fields.MarkdownField(
                blank=True, property_suffix="_markdown"
            ),
        ),
    ]
