# Generated by Django 2.1.4 on 2018-12-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_use_markdown_field"),
        ("api", "0030_merge_20181220_2121"),
    ]

    operations = []
