# Generated by Django 2.1.4 on 2018-12-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_merge_20181221_1821"),
        ("api", "0032_auto_20181221_1834"),
    ]

    operations = []
