# Generated by Django 2.1.4 on 2018-12-21 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_merge_20181220_2036"),
        ("api", "0033_merge_20181221_1911"),
    ]

    operations = []
