# Generated by Django 2.1.4 on 2019-01-02 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0033_merge_20181221_1911"), ("api", "0030_job_log")]

    operations = []
