# Generated by Django 2.1.4 on 2019-01-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_merge_20190102_2251"),
        ("api", "0034_merge_20181221_2310"),
    ]

    operations = []
