# Generated by Django 2.1.5 on 2019-01-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0035_merge_20190103_2012")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="canceled_at",
            field=models.DateTimeField(
                help_text=(
                    "The time at which the Job canceled itself, likely just a bit "
                    "after it was told to cancel itself."
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preflightresult",
            name="canceled_at",
            field=models.DateTimeField(
                help_text=(
                    "The time at which the Job canceled itself, likely just a bit "
                    "after it was told to cancel itself."
                ),
                null=True,
            ),
        ),
    ]
