# Generated by Django 2.1.5 on 2019-01-16 23:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import metadeploy.api.models


class Migration(migrations.Migration):

    dependencies = [("api", "0036_add_help_text")]

    operations = [
        migrations.AlterModelOptions(
            name="step", options={"ordering": ("step_num", "task_name")}
        ),
        migrations.AlterModelManagers(
            name="user", managers=[("objects", metadeploy.api.models.UserManager())]
        ),
        migrations.RemoveField(model_name="plan", name="flow_name"),
        migrations.RemoveField(model_name="step", name="order_key"),
        migrations.AddField(
            model_name="step",
            name="step_num",
            field=models.CharField(
                default="1.0",
                help_text="dotted step number for CCI task",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="step",
            name="task_class",
            field=models.CharField(
                default="cumulusci.core.tasks.BaseTask",
                help_text="dotted module path to BaseTask implementation",
                max_length=2048,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="step",
            name="task_config",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="name",
            field=models.CharField(help_text="Customer facing label", max_length=1024),
        ),
        migrations.AlterField(
            model_name="step",
            name="task_name",
            field=models.CharField(help_text="CCI Config task_name", max_length=64),
        ),
    ]
