# Generated by Django 2.1.5 on 2019-01-17 15:56

from django.db import migrations

import metadeploy.api.models


class Migration(migrations.Migration):

    dependencies = [("api", "0036_add_help_text")]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", metadeploy.api.models.UserManager())]
        )
    ]
