# Generated by Django 2.1.5 on 2019-01-22 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0037_user_manager")]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="visible_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.AllowedList",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="visible_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.AllowedList",
            ),
        ),
    ]
