# Generated by Django 2.1.5 on 2019-01-24 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0037_user_manager")]

    operations = [
        migrations.CreateModel(
            name="AllowedListOrg",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", models.CharField(max_length=18)),
                (
                    "description",
                    models.TextField(
                        help_text=("A description of the org for future reference",)
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(model_name="allowedlist", name="organization_ids"),
        migrations.AddField(
            model_name="allowedlistorg",
            name="allowed_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orgs",
                to="api.AllowedList",
            ),
        ),
        migrations.AddField(
            model_name="allowedlistorg",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
