# Generated by Django 2.1.5 on 2019-01-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0037_auto_20190116_2318")]

    operations = [
        migrations.AddField(
            model_name="step",
            name="path",
            field=models.CharField(
                default="root",
                help_text="dotted path e.g. flow1.flow2.task_name",
                max_length=2048,
            ),
            preserve_default=False,
        )
    ]
