# Generated by Django 2.1.5 on 2019-01-22 00:18

import django.db.models.expressions
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0040_auto_20190121_2345")]

    operations = [
        migrations.AlterModelOptions(
            name="step",
            options={
                "ordering": (
                    django.db.models.expressions.Func(
                        django.db.models.expressions.F("step_num"),
                        extra=".",
                        function="string_to_array",
                    ),
                )
            },
        )
    ]
