# Generated by Django 2.1.5 on 2019-01-24 16:16

import django.db.models.deletion
import django.db.models.expressions
import sfdo_template_helpers.fields
from django.db import migrations, models

import metadeploy.api.models


class Migration(migrations.Migration):

    dependencies = [("api", "0041_auto_20190122_0018_squashed_0045_auto_20190122_0025")]

    operations = [
        migrations.AlterModelOptions(
            name="step",
            options={
                "ordering": (
                    metadeploy.api.models.DottedArray(
                        django.db.models.expressions.F("step_num")
                    ),
                )
            },
        ),
        migrations.AlterField(
            model_name="plan",
            name="visible_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.AllowedList",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=sfdo_template_helpers.fields.MarkdownField(
                blank=True, property_suffix="_markdown"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="visible_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.AllowedList",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="kind",
            field=models.CharField(
                choices=[
                    ("metadata", "Metadata"),
                    ("onetime", "One Time Apex"),
                    ("managed", "Managed Package"),
                    ("data", "Data"),
                    ("other", "Other"),
                ],
                default="metadata",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="version", name="description", field=models.TextField(blank=True)
        ),
    ]
