# Generated by Django 2.1.5 on 2019-01-22 00:21

import django.db.models.expressions
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0041_auto_20190122_0018")]

    operations = [
        migrations.AlterModelOptions(
            name="step",
            options={
                "ordering": (
                    django.db.models.expressions.Func(
                        django.db.models.expressions.F("step_num"),
                        extras=".",
                        function="string_to_array",
                    ),
                )
            },
        )
    ]
