# Generated by Django 2.1.5 on 2019-01-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_auto_20190124_1616"),
        ("api", "0038_plan_product_visible_to_blank"),
    ]

    operations = []
