# Generated by Django 2.1.5 on 2019-01-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_auto_20190124_1900"),
        ("api", "0043_merge_20190124_1852"),
    ]

    operations = []
