# Generated by Django 2.1.5 on 2019-01-22 00:25

import django.db.models.expressions
from django.db import migrations

import metadeploy.api.models


class Migration(migrations.Migration):

    dependencies = [("api", "0044_auto_20190122_0023")]

    operations = [
        migrations.AlterModelOptions(
            name="step",
            options={
                "ordering": (
                    metadeploy.api.models.DottedArray(
                        django.db.models.expressions.F("step_num"), extra="."
                    ),
                )
            },
        )
    ]
