# Generated by Django 2.1.5 on 2019-01-28 21:04

import sfdo_template_helpers.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0044_merge_20190125_1502")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="license_requirements",
            field=sfdo_template_helpers.fields.MarkdownField(
                blank=True, property_suffix="_markdown"
            ),
        )
    ]
