# Generated by Django 2.1.5 on 2019-01-28 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0045_product_license_requirements")]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="license_requirements",
            new_name="click_through_agreement",
        )
    ]
