# Generated by Django 2.1.5 on 2019-01-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0046_rename_license_requirements")]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.TextField(blank=True),
        )
    ]
