# Generated by Django 2.1.5 on 2019-02-04 19:29

import django.db.models.deletion
import sfdo_template_helpers.fields
from django.db import migrations, models


def forwards(apps, schema_editor):
    Product = apps.get_model("api", "Product")
    for product in Product.objects.all():
        product.translations.create(
            language_code="en-us",
            title=product.title,
            description=product.description,
            short_description=product.short_description,
            click_through_agreement=product.click_through_agreement,
        )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("api", "0047_product_short_description")]

    operations = [
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "description",
                    sfdo_template_helpers.fields.MarkdownField(
                        blank=True, property_suffix="_markdown"
                    ),
                ),
                ("short_description", models.TextField(blank=True)),
                (
                    "click_through_agreement",
                    sfdo_template_helpers.fields.MarkdownField(
                        blank=True, property_suffix="_markdown"
                    ),
                ),
            ],
            options={
                "verbose_name": "product Translation",
                "db_table": "api_product_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="producttranslation",
            name="master",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="api.Product",
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(model_name="product", name="click_through_agreement"),
        migrations.RemoveField(model_name="product", name="description"),
        migrations.RemoveField(model_name="product", name="short_description"),
        migrations.RemoveField(model_name="product", name="title"),
        migrations.AlterUniqueTogether(
            name="producttranslation", unique_together={("language_code", "master")}
        ),
    ]
