# Generated by Django 2.1.5 on 2019-02-12 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0049_add_all_other_translations")]

    operations = [
        migrations.CreateModel(
            name="ClickthroughText",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="click_through_agreement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.ClickthroughText",
            ),
        ),
    ]
