# Generated by Django 2.1.5 on 2019-02-12 17:22

import django.db.models.deletion
import parler.models
import sfdo_template_helpers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0049_add_all_other_translations")]

    operations = [
        migrations.CreateModel(
            name="PlanTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={"abstract": False},
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PlanTemplateTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "preflight_message",
                    sfdo_template_helpers.fields.MarkdownField(
                        blank=True, property_suffix="_markdown"
                    ),
                ),
                (
                    "post_install_message",
                    sfdo_template_helpers.fields.MarkdownField(
                        blank=True, property_suffix="_markdown"
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="api.PlanTemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "plan template Translation",
                "db_table": "api_plantemplate_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
            },
        ),
        migrations.RenameField(
            model_name="plantranslation",
            old_name="post_install_message",
            new_name="post_install_message_additional",
        ),
        migrations.RenameField(
            model_name="plantranslation",
            old_name="preflight_message",
            new_name="preflight_message_additional",
        ),
        migrations.AddField(
            model_name="plan",
            name="plan_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.PlanTemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plantemplatetranslation",
            unique_together={("language_code", "master")},
        ),
    ]
