# Generated by Django 2.1.5 on 2019-02-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0050_add_plan_template")]

    operations = [
        migrations.AddField(
            model_name="plantemplate",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        )
    ]
