# Generated by Django 2.1.7 on 2019-02-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_add_clickthrough_agreement"),
        ("api", "0051_plantemplate_name"),
    ]

    operations = []
