# Generated by Django 2.1.5 on 2019-02-07 21:07

import django.db.models.deletion
import sfdo_template_helpers.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0051_copy_plan_to_plan_template")]

    operations = [
        migrations.RemoveField(
            model_name="plantranslation", name="post_install_message"
        ),
        migrations.RemoveField(model_name="plantranslation", name="preflight_message"),
        migrations.AddField(
            model_name="plantranslation",
            name="post_install_message_additional",
            field=sfdo_template_helpers.fields.MarkdownField(
                blank=True, property_suffix="_markdown"
            ),
        ),
        migrations.AddField(
            model_name="plantranslation",
            name="preflight_message_additional",
            field=sfdo_template_helpers.fields.MarkdownField(
                blank=True, property_suffix="_markdown"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="plan_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.PlanTemplate"
            ),
        ),
    ]
