# Generated by Django 2.1.5 on 2019-02-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0050_encrypt_tokens"), ("api", "0051_plantemplate_name")]

    operations = []
