# Generated by Django 2.1.7 on 2019-02-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_merge_20190213_1447"),
        ("api", "0052_merge_20190213_1501"),
    ]

    operations = []
