# Generated by Django 2.1.7 on 2019-03-01 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0055_no_null_plan_template")]

    operations = [
        migrations.AddField(
            model_name="planslug",
            name="new_parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.PlanTemplate",
            ),
        )
    ]
