# Generated by Django 2.1.7 on 2019-03-01 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0057_copy_over_plan_slug")]

    operations = [
        migrations.RemoveField(model_name="planslug", name="parent"),
        migrations.RenameField(
            model_name="planslug", old_name="new_parent", new_name="parent"
        ),
        migrations.AlterField(
            model_name="planslug",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.PlanTemplate"
            ),
        ),
    ]
