# Generated by Django 2.1.7 on 2019-03-04 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0058_move_plan_slug_parent")]

    operations = [
        migrations.AddField(
            model_name="plantemplate",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.Product",
            ),
        )
    ]
