# Generated by Django 2.1.7 on 2019-03-04 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0060_add_product_to_plantemplate")]

    operations = [
        migrations.AlterField(
            model_name="plantemplate",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.Product"
            ),
        )
    ]
