# Generated by Django 2.1.7 on 2019-03-11 21:24

from django.db import migrations


def forwards(apps, schema_editor):
    SiteProfile = apps.get_model("api", "SiteProfile")
    Site = apps.get_model("sites", "Site")
    for site in Site.objects.all():
        SiteProfile.objects.create(site=site, name=site.name)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("api", "0062_add_site_profile")]

    operations = [migrations.RunPython(forwards, backwards)]
