# Generated by Django 2.1.7 on 2019-03-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0063_populate_site_profile")]

    operations = [
        migrations.RemoveField(model_name="siteprofile", name="logo"),
        migrations.AddField(
            model_name="siteprofile",
            name="company_logo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="favicon",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="product_logo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="siteprofiletranslation",
            name="company_name",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
