# Generated by Django 2.2 on 2019-04-15 16:00

import sfdo_template_helpers.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0064_improve_site_profile")]

    operations = [
        migrations.AddField(
            model_name="plantemplatetranslation",
            name="error_message",
            field=sfdo_template_helpers.fields.MarkdownField(
                blank=True, property_suffix="_markdown"
            ),
        ),
        migrations.AddField(
            model_name="producttranslation",
            name="error_message",
            field=sfdo_template_helpers.fields.MarkdownField(
                blank=True, property_suffix="_markdown"
            ),
        ),
    ]
