# Generated by Django 2.1.7 on 2019-03-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0064_improve_site_profile")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="success_at",
            field=models.DateTimeField(
                help_text=(
                    "If the job completed successfully, the time of that success."
                ),
                null=True,
            ),
        )
    ]
