# Generated by Django 2.2 on 2019-04-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_remove_blank_choice_from_allowedlist"),
        ("api", "0065_add_error_messages"),
    ]

    operations = []
