# Generated by Django 2.2 on 2019-04-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_merge_20190415_1610"),
        ("api", "0067_allowedlist_org_type_help_text"),
    ]

    operations = []
