# Generated by Django 2.2 on 2019-04-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0067_allowedlist_org_type_help_text")]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="preflight_flow_name",
            field=models.CharField(
                blank=True,
                help_text="If this is blank, the Plan requires no preflight.",
                max_length=256,
            ),
        )
    ]
