# Generated by Django 2.2 on 2019-04-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_merge_20190415_1806"),
        ("api", "0068_add_help_text_to_plan"),
    ]

    operations = []
