# Generated by Django 2.2 on 2019-04-30 20:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0069_merge_20190418_2028")]

    operations = [
        migrations.AlterField(
            model_name="allowedlist",
            name="org_type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Production", "Production"),
                        ("Scratch", "Scratch"),
                        ("Sandbox", "Sandbox"),
                        ("Developer", "Developer"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                help_text="All orgs of these types will be automatically allowed.",
                size=4,
            ),
        )
    ]
