# Generated by Django 2.2 on 2019-05-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_job_success_at"),
        ("api", "0071_fix_socialaccount_uids"),
    ]

    operations = []
