# Generated by Django 2.2.1 on 2019-05-09 19:27

from django.db import migrations, models


def forwards(apps, schema_editor):
    # Add org id directly to jobs & preflightresults
    # so they can be queried by it
    SocialAccount = apps.get_model("socialaccount", "SocialAccount")
    user_id_to_org_id = {}
    for sa in SocialAccount.objects.all():
        user_id_to_org_id[str(sa.user_id)] = sa.extra_data["organization_details"]["Id"]

    Job = apps.get_model("api", "Job")
    for job in Job.objects.all():
        user_id = str(job.user_id)
        org_id = user_id_to_org_id.get(user_id)
        if org_id:
            job.org_id = org_id
            job.save()

    PreflightResult = apps.get_model("api", "PreflightResult")
    for preflightresult in PreflightResult.objects.all():
        user_id = str(preflightresult.user_id)
        org_id = user_id_to_org_id.get(user_id)
        if org_id:
            preflightresult.org_id = org_id
            preflightresult.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("api", "0072_merge_20190504_1506")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="org_id",
            field=models.CharField(null=True, blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name="preflightresult",
            name="org_id",
            field=models.CharField(null=True, blank=True, max_length=18),
        ),
        migrations.RunPython(forwards, backwards),
    ]
