# Generated by Django 2.2.1 on 2019-05-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0072_merge_20190504_1506")]

    operations = [
        migrations.AddField(
            model_name="allowedlist",
            name="list_for_allowed_by_orgs",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "If a user is allowed only because they have the right Org Type, "
                    "should this be listed for them? If not, they can still find it if "
                    "they happen to know the address."
                ),
            ),
        )
    ]
