# Generated by Django 2.2.1 on 2019-05-10 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0073_allowedlist_list_for_allowed_by_orgs"),
        ("api", "0073_org_id"),
    ]

    operations = []
