# Generated by Django 2.2.1 on 2019-05-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0074_merge_20190510_0230")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="full_org_type",
            field=models.CharField(blank=True, max_length=256, null=True),
        )
    ]
