# Generated by Django 2.2.4 on 2019-08-13 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0077_auto_20190805_1609")]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="step_num",
            field=models.CharField(
                help_text="dotted step number for CCI task",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(regex="^[\\d\\./]+$")
                ],
            ),
        )
    ]
