# Generated by Django 2.2.5 on 2019-10-16 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0078_step_num_validator")]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="api.Plan",
            ),
        )
    ]
