# Generated by Django 2.2.6 on 2019-10-21 19:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0079_auto_20191016_1448")]

    operations = [
        migrations.AddField(
            model_name="step",
            name="source",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        )
    ]
