# Generated by Django 2.2.10 on 2020-03-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0080_step_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.TextField()),
                ("slug", models.TextField()),
                ("text", models.TextField()),
                ("lang", models.CharField(max_length=5)),
            ],
        ),
    ]
