# Generated by Django 2.2.10 on 2020-03-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0081_translation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("context", "slug", "lang")},
        ),
    ]
