# Generated by Django 2.2.11 on 2020-04-07 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0083_plan_uniqueness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allowedlistorg",
            name="allowed_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orgs",
                to="api.AllowedList",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="canceled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The time at which the Job canceled itself, likely just a bit after it was told to cancel itself.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="exception",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="success_at",
            field=models.DateTimeField(
                blank=True,
                help_text="If the job completed successfully, the time of that success.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="visible_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.AllowedList",
            ),
        ),
        migrations.AlterField(
            model_name="planslug",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.PlanTemplate"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="visible_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.AllowedList",
            ),
        ),
        migrations.AlterField(
            model_name="productslug",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.Product"
            ),
        ),
    ]
