# Generated by Django 2.2.12 on 2020-05-20 20:44

import github3
from django.conf import settings
from django.db import migrations, models
from django.utils.dateparse import parse_datetime

from metadeploy.api.cci_configs import extract_user_and_repo

DEFAULT_TIMESTAMP = parse_datetime("2019-01-01T00:00:00Z")


def populate_created_at(apps, schema_editor):
    model = apps.get_model("api", "Plan")

    repos = {}
    gh = github3.login(token=settings.GITHUB_TOKEN)

    for plan in model.objects.all():
        try:
            repo_url = plan.version.product.repo_url
            if repo_url not in repos:
                gh_user, repo_name = extract_user_and_repo(repo_url)
                repos[repo_url] = gh.repository(gh_user, repo_name)
            repo_api = repos[repo_url]
            commit = repo_api.commit(plan.version.commit_ish).commit
            dt = parse_datetime(commit["author"]["date"])
        except Exception:
            dt = DEFAULT_TIMESTAMP
        plan.created_at = dt
        plan.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0086_socialaccount_cleanup"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="plan", name="unique_version_plan_template",
        ),
        migrations.RemoveConstraint(
            model_name="plan", name="unique_version_primary_plan",
        ),
        migrations.AddField(
            model_name="plan",
            name="commit_ish",
            field=models.CharField(
                blank=True,
                help_text="This is usually a tag, sometimes a branch. Use this to optionally override the Version's commit_ish.",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(populate_created_at, backwards),
        migrations.AlterField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
