# Generated by Django 2.2.12 on 2020-05-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0087_plan_revisions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
