# Generated by Django 2.2.15 on 2020-08-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0088_auto_20200521_1652"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="supported_orgs",
            field=models.CharField(
                choices=[
                    ("Persistent", "Persistent"),
                    ("Scratch", "Scratch"),
                    ("Both", "Both"),
                ],
                default="Persistent",
                max_length=32,
            ),
        ),
    ]
