# Generated by Django 2.2.15 on 2020-08-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0088_auto_20200521_1652"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
