# Generated by Django 2.2.15 on 2020-08-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0088_auto_20200521_1652"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="make_scratch_org",
            field=models.BooleanField(default=False),
        ),
    ]
