# Generated by Django 2.2.15 on 2020-08-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0089_plan_supported_orgs"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="org_name",
            field=models.CharField(default="release", max_length=64),
        ),
    ]
