# Generated by Django 2.2.16 on 2020-10-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0090_convert_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="org_name",
        ),
        migrations.RemoveField(
            model_name="job",
            name="organization_url",
        ),
        migrations.RemoveField(
            model_name="preflightresult",
            name="organization_url",
        ),
    ]
