# Generated by Django 2.2.15 on 2020-08-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0090_plan_org_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="org_name",
            field=models.CharField(blank=True, default="release", max_length=64),
        ),
    ]
