# Generated by Django 2.2.15 on 2020-08-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0089_plan_order"),
        ("api", "0091_auto_20200821_1833"),
    ]

    operations = []
