# Generated by Django 2.2.15 on 2020-09-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0093_nullable_user_on_job"),
        ("api", "0093_scratchorgjob"),
    ]

    operations = []
