# Generated by Django 2.2.16 on 2020-11-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0094_auto_20201027_1927"),
    ]

    operations = [
        migrations.AddField(
            model_name="preflightresult",
            name="log",
            field=models.TextField(blank=True),
        ),
    ]
