# Generated by Django 2.2.15 on 2020-09-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0095_scratchorgjob_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preflightresult",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scratchorgjob", name="uuid", field=models.UUIDField(null=True),
        ),
    ]
