# Generated by Django 2.2.15 on 2020-09-24 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0096_add_uuid_pseudoauth_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preflightresult",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
