# Generated by Django 2.2.16 on 2020-10-01 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0098_use_org_id_consistently"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ScratchOrgJob",
            new_name="ScratchOrg",
        ),
    ]
