# Generated by Django 2.2.16 on 2020-10-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0099_rename_scratch_org_job"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="org_name",
            new_name="org_config_name",
        ),
    ]
