# Generated by Django 2.2.16 on 2020-10-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0100_rename_plan_org_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scratchorg",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
