# Generated by Django 2.2.16 on 2020-11-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0101_scratch_org_nullable_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="layout",
            field=models.CharField(
                choices=[("Default", "Default"), ("Card", "Card")],
                default="Default",
                max_length=64,
            ),
        ),
    ]
