# Generated by Django 2.2.16 on 2020-11-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0102_product_layout"),
        ("api", "0102_merge_20201023_1733"),
    ]

    operations = []
