# Generated by Django 2.2.16 on 2020-11-08 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0094_auto_20201027_1927"),
        ("api", "0103_merge_20201106_1627"),
    ]

    operations = []
