# Generated by Django 2.2.16 on 2020-11-11 20:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0104_merge_20201108_0329"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scratchorg",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
