# Generated by Django 2.2.16 on 2020-11-11 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_merge_20201108_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratchorg',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
