# Generated by Django 2.2.16 on 2020-11-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0106_productcategorytranslation"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
