# Generated by Django 2.2.16 on 2020-11-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0109_plan_scratch_org_duration_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="scratchorg",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
