# Generated by Django 2.2.16 on 2020-11-20 23:07

from django.db import migrations

from metadeploy.api.belvedere_utils import convert_to_18


def convert_org_id_to_18(apps, schema_editor):
    """
    Use 18-char IDs to better match the Salesforce API
    """
    Job = apps.get_model("api", "Job")
    ScratchOrg = apps.get_model("api", "ScratchOrg")
    PreflightResult = apps.get_model("api", "PreflightResult")

    for org in ScratchOrg.objects.exclude(org_id__isnull=True):
        old_id = org.org_id
        new_id = convert_to_18(old_id)

        org.org_id = new_id
        org.save()
        Job.objects.filter(org_id=old_id).update(org_id=new_id)
        PreflightResult.objects.filter(org_id=old_id).update(org_id=new_id)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0110_scratchorg_expires_at"),
    ]

    operations = [
        migrations.RunPython(
            convert_org_id_to_18, reverse_code=migrations.RunPython.noop
        )
    ]
