# Generated by Django 2.2.16 on 2020-11-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0111_scratch_org_id_to_18"),
        ("api", "0095_preflightresult_log"),
    ]

    operations = []
