# Generated by Django 3.1.13 on 2021-08-19 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0114_plan_calculated_average_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="calculated_average_duration",
            field=models.IntegerField(
                blank=True,
                help_text="The duration between the enqueueing of a job and its successful completion.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Average duration of a plan (seconds)",
            ),
        ),
    ]
