# Generated by Django 3.1.13 on 2021-10-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0115_plan_calculated_average_duration_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_release_test",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="preflightresult",
            name="is_release_test",
            field=models.BooleanField(default=False),
        ),
    ]
