# Generated by Django 3.1.14 on 2022-01-14 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0118_auto_20220107_2358"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="master_service_agreement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="msa_jobs",
                to="api.clickthroughagreement",
            ),
        ),
    ]
