# Generated by Django 3.2.14 on 2022-09-08 22:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_auto_20220527_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='TubularJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='tubular_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tubularjob'),
        ),
    ]
