# Generated by Django 3.2.14 on 2022-07-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0121_add_multi_tenancy"),
        ("api", "0121_add_product_tags"),
    ]

    operations = []
