# Generated by Django 3.2.13 on 2022-06-08 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("api", "0121_add_multi_tenancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowedlist",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translation",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sites.site"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("site", "context", "slug", "lang")},
        ),
    ]
