# Generated by Django 3.2.13 on 2022-06-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0122_more_multi_tenancy_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="site",
        ),
    ]
