# Generated by Django 4.1 on 2022-09-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0122_add_multi_tenancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_persistent",
            field=models.BooleanField(
                default=False,
                help_text="Denotes whether a user should be skipped when the delete_old_users job executes.",
            ),
        ),
    ]
