# Generated by Django 4.1 on 2023-11-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0123_user_do_not_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="allowed_ip_addresses",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
