# Generated by Django 3.2.13 on 2022-06-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("api", "0124_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allowedlist",
            name="title",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="productslug",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name="allowedlist",
            unique_together={("site", "title")},
        ),
    ]
