name: Production Smoke Test

on:
  repository_dispatch:
    types: [heroku-release-phase]

env:
  CUMULUSCI_KEY: ${{ secrets.CUMULUSCI_KEY }}

jobs:
  production_smoke_test:
    name: 'Production Post-Deploy Smoke Test'
    runs-on: SFDO-Tooling-Ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install sfdx
        run: |
          mkdir sfdx
          wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
          ./sfdx/install
          echo $SFDX_HUB_KEY_BASE64 | base64 --decode > sfdx.key
          sfdx force:auth:jwt:grant --clientid $SFDX_CLIENT_ID --jwtkeyfile sfdx.key --username $SFDX_HUB_USERNAME --setdefaultdevhubusername -a hub
        env:
          SFDX_HUB_KEY_BASE64: ${{ secrets.SFDX_HUB_KEY_BASE64 }}
          SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID }}
          SFDX_HUB_USERNAME: ${{ secrets.SFDX_HUB_USERNAME }}

      - name: Install CumulusCI
        run: pip install cumulusci

      - name: Create test org
        run: cci org info enterprise

      - name: Deploy Trusted IP Ranges
        run:
          cci task run deploy --org enterprise -o path robot/trusted_ip_ranges

      - name: Wait for Heroku Dynos to Restart
        run: sleep 5m

      - name: Run robot test
        run: |
          cci task run robot \
            --org enterprise \
            -o suites robot/tasks/run_plan.robot \
            -o vars BROWSER:headlesschrome,LANG:en,PRODUCT:program-management,PLAN:install,BASE_URL:https://install.salesforce.org

      - name: Delete scratch org
        if: always()
        run: cci org scratch_delete enterprise

      - name: Store robot results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: robot
          path: robot/results
